<h1><?=$this->escapeHtml($title) ?></h1>
<p>
    <a href="<?=$this->urlAdd?>">Nova Renda</a>
    <a href="<?=$this->urlAddRendaExtra?>">Renda Extra</a>
</p>
<table class="table">
    <tr>
        <th>Valor</th>
        <th>Tipo Renda</th>
        <th>Mes</th>
        <th>&nbsp;</th>
    </tr>

    <?=$this->partialLoop('despesas/renda/rendas.phtml', $this->paginator) ?>
</table>

<p>

    <?=$this->paginationControl($this->paginator,
        'Sliding',
        'pagination', array('route' => 'renda')); ?>
</p>

<p>
    <a href="<?=$this->urlHomepage?>">Voltar</a>
</p>

