<?php

namespace Despesas\Proxy\__CG__\Despesas\Model;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Renda extends \Despesas\Model\Renda implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Despesas\\Model\\Renda' . "\0" . 'id', '' . "\0" . 'Despesas\\Model\\Renda' . "\0" . 'uid', '' . "\0" . 'Despesas\\Model\\Renda' . "\0" . 'valor', '' . "\0" . 'Despesas\\Model\\Renda' . "\0" . 'tipoRenda', '' . "\0" . 'Despesas\\Model\\Renda' . "\0" . 'rendaExtra', '' . "\0" . 'Despesas\\Model\\Renda' . "\0" . 'mes', '' . "\0" . 'Despesas\\Model\\Renda' . "\0" . 'mesRef', 'inputFilter');
        }

        return array('__isInitialized__', '' . "\0" . 'Despesas\\Model\\Renda' . "\0" . 'id', '' . "\0" . 'Despesas\\Model\\Renda' . "\0" . 'uid', '' . "\0" . 'Despesas\\Model\\Renda' . "\0" . 'valor', '' . "\0" . 'Despesas\\Model\\Renda' . "\0" . 'tipoRenda', '' . "\0" . 'Despesas\\Model\\Renda' . "\0" . 'rendaExtra', '' . "\0" . 'Despesas\\Model\\Renda' . "\0" . 'mes', '' . "\0" . 'Despesas\\Model\\Renda' . "\0" . 'mesRef', 'inputFilter');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Renda $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getMesRef()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMesRef', array());

        return parent::getMesRef();
    }

    /**
     * {@inheritDoc}
     */
    public function setMesRef($mesRef)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMesRef', array($mesRef));

        return parent::setMesRef($mesRef);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', array($id));

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getUid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUid', array());

        return parent::getUid();
    }

    /**
     * {@inheritDoc}
     */
    public function setUid($uid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUid', array($uid));

        return parent::setUid($uid);
    }

    /**
     * {@inheritDoc}
     */
    public function getValor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getValor', array());

        return parent::getValor();
    }

    /**
     * {@inheritDoc}
     */
    public function setValor($valor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setValor', array($valor));

        return parent::setValor($valor);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipoRenda()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipoRenda', array());

        return parent::getTipoRenda();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipoRenda($tipoRenda)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipoRenda', array($tipoRenda));

        return parent::setTipoRenda($tipoRenda);
    }

    /**
     * {@inheritDoc}
     */
    public function getRendaExtra()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRendaExtra', array());

        return parent::getRendaExtra();
    }

    /**
     * {@inheritDoc}
     */
    public function setRendaExtra($rendaExtra)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRendaExtra', array($rendaExtra));

        return parent::setRendaExtra($rendaExtra);
    }

    /**
     * {@inheritDoc}
     */
    public function getMes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMes', array());

        return parent::getMes();
    }

    /**
     * {@inheritDoc}
     */
    public function setMes($mes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMes', array($mes));

        return parent::setMes($mes);
    }

    /**
     * {@inheritDoc}
     */
    public function exchangeArray($array)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'exchangeArray', array($array));

        return parent::exchangeArray($array);
    }

    /**
     * {@inheritDoc}
     */
    public function getArrayCopy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArrayCopy', array());

        return parent::getArrayCopy();
    }

    /**
     * {@inheritDoc}
     */
    public function getInputFilter()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInputFilter', array());

        return parent::getInputFilter();
    }

}
