<h1><?=$this->escapeHtml($title) ?></h1>
<p>
    <a href="<?=$this->urlAdd?>">Novo Setor</a>
</p>
<table class="table">
    <tr>
        <th>Codigo</th>
        <th>Nome</th>
        <th>&nbsp;</th>
    </tr>

    <!-- exibiçao com partial
    -->
    <?=$this->partialLoop('tropa/setor/setores.phtml', $this->paginator) ?>
</table>

    <p>

    <?=$this->paginationControl($this->paginator,
                                'Sliding',
                                'pagination', array('route' => 'setor')); ?>
    </p>

<p>
    <a href="<?=$this->urlHomepage?>">Voltar</a>
</p>