<style>
    .resumo-donativo{
        background-color: #FAF9F9;
        padding: 8px;
        margin-bottom: 14px;
        box-shadow: 0px 0px 1px #CCC;
    }
</style>

<?php
use Application\Entity\Donativos;

$form = $this->form;
$form->prepare();
?>

<?php
/** @var Donativos $donativo */
$donativo = $this->donativo;

$instituicao = $donativo->getInstituicao()->getNomeFantasia();
$cnpj = $donativo->getInstituicao()->getCnpj();
$qtd = $donativo->getQuantidade();
$dataDesa = $donativo->getDataDesa()->format('d/m/Y');
$produto = $donativo->getTitulo();
$categoria = $donativo->getIdCategoria()->getDescricao();

echo '<div class="resumo-donativo">';
echo '<p><strong class="text-info">Resumo Donativo</strong></p>';
echo "<p><strong>Instituicao:</strong> $instituicao </p>";
echo "<p><strong>CNPJ:</strong> $cnpj </p>";
echo "<p><strong>Unidades:</strong> $qtd</p>";
echo "<p><strong>Data desativação:</strong> $dataDesa</p>";
echo "<p><strong>Produto:</strong> $produto</p>";
echo "<p><strong>Categoria:</strong> $categoria</p>";
echo '</div>';

?>

<?php echo $this->form()->openTag($form) ?>
<?=$this->formInput($form->get('idTransacao'))?>
<?=$this->formInput($form->get('idDonativo'))?>
<?=$this->formInput($form->get('idInstituicao'))?>
<?=$this->formInput($form->get('idPessoa'))?>
<?=$this->formInput($form->get('idMensagem'))?>
<?=$this->formInput($form->get('dataTransacao'))?>
<?=$this->formInput($form->get('dataEnvioMensagem'))?>


<?=$this->formLabel($form->get('quantidadeOferecida'))?>
<?=$this->formInput($form->get('quantidadeOferecida'))?>


<?=$this->formLabel($form->get('mensagem'))?>
<?=$this->formTextarea($form->get('mensagem'))?>


<div class="modal-footer">
<button id="#btn-confirmar" type="submit" class="btn btn-success">Confirmar</button>
<button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
</div>

<?php echo $this->form()->closeTag($form) ?>