

<?php
$form = $this->form;
//$form->setAttribute('action', $this->urlAction);
$form->prepare();


?>

<?=$this->form()->openTag($form)?>

<?=$this->formRow($form->get('id'))?>
<?=$this->formRow($form->get('uid'))?>
<?=$this->formRow($form->get('descDespesa'))?>
<?=$this->formRow($form->get('valor'))?>
<?=$this->formRow($form->get('tipoDespesa'))?>
<?=$this->formRow($form->get('renda'))?>
<?=$this->formRow($form->get('data'))?>

<div class="modal-footer">
    <?=$this->formRow($form->get('submit'))?>
    <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>

</div>


<?=$this->form()->closeTag()?>

<script>
    $(document).ready(function(){

        //console.log(retornoController);
        $('#despesa').submit(function(){
            event.preventDefault ? event.preventDefault() : event.returnValue = false;


           $.ajax({
               data: 'descDespesa=' + $('#descDespesa').val() + '&valor=' + $('#valor').val() + '&uid=' +
               $("input[name='uid']").val() + '&tipoDespesa=' + $('#tipoDespesa').val() + '&renda=' + $('#renda').val() + '&data=' + $('#data').val() ,
               type: 'POST',
               url:'http://despesas/despesa/add',
               success: function (retorno) {

                    console.log(retorno);
                    if(retorno.retorno == 'erro'){
                        //aplicar estilo
                        alert('Erro ao incluir dados');
                    }else{
                        $('#myModal').modal('hide');
                        $('.modal-body').html('');

                    }

               }

           });
           /**/
       });


    });


</script>


<?=$this->retorno?>
