
<tr>
    <td>
        <a  class="btn btn-primary btn-small alterarDespesa" data-toggle="modal" data-target="#myModal"
            despesaId = "<?php echo $this->model->getId() ?>"
            href="">
            <i class="glyphicon glyphicon-edit"></i>
            Editar</a>

        <a  class="btn btn-danger btn-small excluirDespesa" data-toggle="modal" data-target="#myModal"
            despesaId = "<?php echo $this->model->getId() ?>"
            href="">
            <i class="glyphicon glyphicon-trash"></i>
            Excluir</a>
        <?php
        //var_dump($this->model->getId());
        ?>
    </td>
    <td><?=$this->escapeHtml($this->model->getDescDespesa())?></td>
    <td><?=$this->model->getValor()?></td>
    <td><?=$this->model->getData()?></td>
    <td><?=$this->model->getTipoDespesa()->getDesc() ?></td>
    <!-- <td><?//=$this->model->getDespesaFixa() ?></td>
    <td><?//=$this->model->getDataFim() ?></td> -->

</tr>
