

<?php
//var_dump($form->get('tipoDespesa'));
//var_dump($form->get('tipoDespesa')->getValue()->getId()) ;



$form = $this->form;
//var_dump($form->get('tipoDespesa')) ;

//$form->setAttribute('action', $this->urlAction);
$form->prepare();
?>

<?=$this->form()->openTag($form)?>
    <?=$this->formRow($form->get('id'))?>
    <?=$this->formRow($form->get('uid'))?>
    <?=$this->formRow($form->get('descDespesa'))?>
    <?=$this->formRow($form->get('valor'))?>
    <?=$this->formRow($form->get('tipoDespesa'))?>
<?=$this->formRow($form->get('renda'))?>
    <?=$this->formRow($form->get('data')->setValue($this->model->getData('Y-m-d')))?>

<div class="modal-footer">
    <?=$this->formRow($form->get('submit'))?>
    <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
</div>
<?=$this->form()->closeTag()?>

<script>
    $(document).ready(function(){
        //  $("#nascimento").mask("99/99/9999");
        //$('#valor').mask('99,99');
    });

</script>
