<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/styles.css')
                        ->prependStylesheet($this->basePath() . '/css/flat.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>


        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
        <nav class="navbar navbar-fixed-top header navbar-default">
            <div class="navbar-inverse-flat col-xs-12">
            	<a href="/" class="navbar-brand padrao-header"><img src="/img/logo.png" height="30" /></a>
                <div class="btn-group btn-group-sm navbar navbar-right margin-bottom-zero">
                	<a href="<?php echo $this->url("instituicao",array('controller'=>'Instituicao','action'=>'index'));?>" class="btn"><i class="glyphicon glyphicon-home"></i> Instituição</a>
                    <a id="btnLogin" role="button" data-toggle="modal" data-target="#loginModal" class="btn"><i class="glyphicon glyphicon-user"></i> Já sou cadastrado</a>
                    <a href="/application/index/cadastrar" class="padrao-login btn"><i class="glyphicon glyphicon-lock"></i> Cadastre-se</a>
                </div>
            </div>

            <div class="col-xs-12" id="subnav">
                <div class="col-xs-12">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse2">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>

                    </div>
                    <div class="collapse navbar-collapse" id="navbar-collapse2">
                        <ul class="nav navbar-nav" style="margin-left: 8%;">
                            <li class="active"><a href="/">Ínicio</a></li>
                            <li><a href="#">Quem Somos?</a></li>
                            <li><a href="#">Por que doar?</a></li>
                            <li><a href="#">Dúvidas</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </nav>

    <div class="container">
        <?php echo $this->content; ?>

        <div id="loginModal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                        <h2 class="form-signin-heading text-center">Acesse e doe agora!</h2>
                    </div>
                    <div class="modal-body">

                    </div>
                </div>
            </div>
        </div>


    </div> <!-- /container -->



    <?php echo $this->inlineScript() ?>

    <footer>
        <hr>
        <div class="col-md-12 text-center"><p><a href="#" target="_ext">Copyright 2015</a></p></div>
        <hr>
    </footer>

    <script>

        $(document).ready(function(){
            $('#btnLogin').click(function(event) {
                $.get("http://pa2015/application/index/modal-login", function(data) {
                    $('.modal-body').html(data);
                });
            });
        });

    </script>

    </body>
</html>
