'<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php
        echo $this->headTitle('Página Inicial - Doacao')->setSeparator(' - ')->setAutoEscape(false);
        echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/styles.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>


        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/doacao/doacao.js')
            ->prependFile($this->basePath() . '/js/jquery-ui.js')
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.js')
            //->prependFile($this->basePath() . '/js/scripts.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
    <div id="spinner">
        <img src="/img/ajax-loader.gif" alt="Loading..."/>
    </div>
    <div class="container" style="margin-top: 6%;">

        <nav class="navbar navbar-fixed-top header">
            <div class="col-md-12">
                <div class="navbar-header">
                    <a href="/" class="navbar-brand padrao-header">Doação</a>
                </div>
                <div class="navbar-header  pull-right">
                    <button id="btnLogin" role="button" data-toggle="modal" data-target="#loginModal" class="navbar-brand btn btn-primary padrao-login">Já sou cadastrado</button>
                    <a href="/user/register" class="navbar-brand  padrao-login btn btn-info">Cadastre-se</a>
                </div>
            </div>

            <div class="navbar navbar-default" id="subnav">
                <div class="col-md-12">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse2">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>

                    </div>
                    <div class="collapse navbar-collapse" id="navbar-collapse2">
                        <ul class="nav navbar-nav" style="margin-left: 8%;">
                            <li class="active"><a href="/">Ínicio</a></li>
                            <li><a href="#">Quem Somos?</a></li>
                            <li><a href="#">Por que doar?</a></li>
                            <li><a href="#">Dúvidas</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </nav>
    <div>




    <div class="container">
        <?php echo $this->content; ?>

        <div id="loginModal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                        <h2 class="form-signin-heading text-center">Acesse e doe agora!</h2>
                    </div>
                    <div class="modal-body">

                    </div>
                </div>
            </div>
        </div>


    </div> <!-- /container -->



    <?php echo $this->inlineScript() ?>

    <footer>
        <hr>
        <div class="col-md-12 text-center"><p><a href="#" target="_ext">Copyright 2015</a></p></div>
        <hr>
    </footer>

    <script>

        $(document).ready(function(){
            $('#btnLogin').click(function(event) {
                $.get("/user/login", function(data) {
                    $('.modal-body').html(data);
                });
            });
        });

    </script>

    </body>
</html>
