<div class="col-lg-6 col-md-6 col-sm-12 label-success padding-zero lista-doador">
<i></i>
<li class="list-group-item"><b>Doadores<span class="glyphicon glyphicon-chevron-down"></span></b></li>
<div style="width: 80px; height: 96px" class="pull-left">
	<img src="/img/logo.jpg" class="border-no-radius img-thumbnail" style="width: 80px; height: 80px;"/></br>
	<label class="label label-default center-block">Hebert Alves</label>
</div>
<div style="width: 80px; height: 96px" class="pull-left">
	<img src="/img/logo.jpg" class="border-no-radius img-thumbnail" style="width: 80px; height: 80px;"/></br>
	<label class="label label-default center-block">Hebert Alves</label>
</div>
<div style="width: 80px; height: 96px" class="pull-left">
	<img src="/img/logo.jpg" class="border-no-radius img-thumbnail" style="width: 80px; height: 80px;"/></br>
	<label class="label label-default center-block">Hebert Alves</label>
</div>
<div style="width: 80px; height: 96px" class="pull-left">
	<img src="/img/logo.jpg" class="border-no-radius img-thumbnail" style="width: 80px; height: 80px;"/></br>
	<label class="label label-default center-block">Hebert Alves</label>
</div>
<div style="width: 80px; height: 96px" class="pull-left">
	<img src="/img/logo.jpg" class="border-no-radius img-thumbnail" style="width: 80px; height: 80px;"/></br>
	<label class="label label-default center-block">Hebert Alves</label>
</div>
<div style="width: 80px; height: 96px" class="pull-left">
	<img src="/img/logo.jpg" class="border-no-radius img-thumbnail" style="width: 80px; height: 80px;"/></br>
	<label class="label label-default center-block">Hebert Alves</label>
</div>
<div style="width: 80px; height: 96px" class="pull-left">
	<img src="/img/logo.jpg" class="border-no-radius img-thumbnail" style="width: 80px; height: 80px;"/></br>
	<label class="label label-default center-block">Hebert Alves</label>
</div>
</div>