<?php 
$data_cadastro = $instituicao->__get('dataCadastro');
if($data_cadastro instanceof  \DateTime)
	$data_cadastro = $data_cadastro->format('d/m/Y');
?>

<title><?php echo $pageTitle." ".$instituicao->__get('razaoSocial')?></title>
<!-- Seção do Perfil  -->
<div class="col-lg-3 col-md-4 col-sm-12 label-primary padding-zero">
	<br>
	<div class="center-block label-default img-circle" style="width: 150px; height: 150px;">
	</div>
	<br>
	<li class="list-group-item" data-toggle="collapse" href="#collapsePerfil" aria-expanded="false" aria-controls="collapsePerfil" style="cursor:pointer;">
		<b>Perfil</b> <span class="glyphicon glyphicon-chevron-down"></span>
	</li>
	<ul class="list-flat list-group collapse in" id="collapsePerfil">
		<li class="list-group-item"><?php echo '<i class="glyphicon glyphicon-user"></i> '.$instituicao->__get('razaoSocial');?></li>
		<li class="list-group-item"><?php echo '<i class="glyphicon glyphicon-credit-card"></i> '.$instituicao->__get('nomeFantasia');?></li>
		<li class="list-group-item"><?php echo '<i class="glyphicon glyphicon-map-marker"></i> '.$instituicao->getEnderecoPrincipal($instituicao->__get('enderecos'))?>
		<li class="list-group-item"><?php echo '<i class="glyphicon glyphicon-bookmark"></i> '.$instituicao->__get('site')?>
		<li class="list-group-item"><?php echo '<i class="glyphicon glyphicon-calendar"></i> '.$data_cadastro?>
	</ul>
	<li class="list-group-item btn-group btn-group-justified" id="rapid-actions">
		<a class="btn" title="Adicionar pedido"><i class="glyphicon glyphicon-plus"></i></a>
		<a class="btn" title="Adicionar pedido"><i class="glyphicon glyphicon-plus"></i></a>
		<a class="btn" title="Adicionar pedido"><i class="glyphicon glyphicon-plus"></i></a>
		<a class="btn" title="Adicionar pedido"><i class="glyphicon glyphicon-plus"></i></a>
	</li>
	<i></i>
</div>
<!-- Fim Perfil -->
<!-- Inicio Atualização rápida -->
<div class="col-sm-12 col-lg-5 col-md-6 padding-zero label-info">
	<!-- Anula o first-child --><i></i>
	<li class="list-group-item">
		<b>Ultimos Pedidos</b>
		<button class="btn btn-xs btn-success pull-right"><span class="glyphicon glyphicon-plus"></span></button>
	</li>
	<?php 
		foreach ($donativos as $donativo):
			echo $donativo;
		endforeach;
	?>
</div>

<div class="col-sm-12 col-lg-4 col-md-6 padding-zero label-success">
	<!-- Anula o first-child --><i></i>
	<li class="list-group-item"><b>Doadores Recentes</b></li>
	<!-- Anula o last-child --><i></i>
	<li class="list-group-item">Silvanyo Santos<button class="btn btn-success btn-xs pull-right">Recebido <i class="glyphicon glyphicon-ok"></i></button></li>
	<ul class="list-group list-flat">
		<li class="list-group-item">
			<b>Quantidade indicada:</b><span class="badge">10</span><br>
			<b>Data abertura: 21-04-205</b></br>
			<b>Donativo: Baixo estoque de nutren</b>
		</li>
	</ul>
		<li class="list-group-item">Silvanyo Santos<button class="btn btn-success btn-xs pull-right">Recebido <i class="glyphicon glyphicon-ok"></i></button></li>
	<ul class="list-group list-flat">
		<li class="list-group-item">
			<b>Quantidade indicada:</b><span class="badge">10</span><br>
			<b>Data abertura: 21-04-205</b></br>
			<b>Donativo: Baixo estoque de nutren</b>
		</li>
	</ul>
		<li class="list-group-item">Silvanyo Santos<button class="btn btn-success btn-xs pull-right">Recebido <i class="glyphicon glyphicon-ok"></i></button></li>
	<ul class="list-group list-flat">
		<li class="list-group-item">
			<b>Quantidade indicada:</b><span class="badge">10</span><br>
			<b>Data abertura: 21-04-205</b></br>
			<b>Donativo: Baixo estoque de nutren</b>
		</li>
	</ul>
</div>