
<br><br><br><br>
<div class="col-xs-12">
    <div class="col-lg-3">
    	<?php echo $perfil;?>
    </div>
    <div class="col-lg-5">
        <div class="panel padding-zero panel-default">
            <i></i>
            <li class="list-group-item-special">
                <b>Donativos</b>
                <button data-toggle="modal" data-item-url="<?php echo $this->url('donativo',array('action'=>'novo')); ?>"
                		data-target="#modal-item" class="btn btn-xs btn-success pull-right" title="Adicionar Donativo">
                	<span class="glyphicon glyphicon-plus"></span>
                </button>
            </li>
            <?php echo $listaDonativos;?>
        </div>
    </div>
    <div class="col-lg-4">
        <div class="panel padding-zero panel-success">
            <i></i>
            <li class="list-group-item-special">
                <b>Doadores Recentes</b>
            </li>
            <li class="list-group-item list-group-item-special">
                <b>Quantidade: <span class="badge" title="Quantidade doada">12</span>
                    <a class="btn btn-xs btn-primary pull-right">Recebido <i class="glyphicon glyphicon-ok"></i></a></b>
            </li>
            <ul class="list-flat list-group">
                <li class="list-group-item list-group-item-special">
                    Hebert Alves da Silva <br>
                    <sub>Data doação: 24/04/2015</sub>
                    <sub>Expira em: 24/05/2015</sub>
                </li>
            </ul>
            <li class="list-group-item list-group-item-special">
                <b>Quantidade: <span class="badge" title="Quantidade doada">12</span>
                    <a class="btn btn-xs btn-primary pull-right">Recebido <i class="glyphicon glyphicon-ok"></i></a></b>
            </li>
            <ul class="list-flat list-group">
                <li class="list-group-item list-group-item-special">
                    Albos Borges <br>
                    <sub>Data doação: 24/04/2015</sub>
                    <sub>Expira em: 24/05/2015</sub>
                </li>
            </ul>
            <li class="list-group-item list-group-item-special">
                <b>Quantidade: <span class="badge" title="Quantidade doada">12</span>
                    <a class="btn btn-xs btn-primary pull-right">Recebido <i class="glyphicon glyphicon-ok"></i></a></b>
            </li>
            <ul class="list-flat list-group">
                <li class="list-group-item list-group-item-special">
                    Wesley Fernando <br>
                    <sub>Data doação: 24/04/2015</sub>
                    <sub>Expira em: 24/05/2015</sub>
                </li>
            </ul>
        </div>
    </div>
    <div class="modal fade" id="modal-item">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-body">
                Corpo Modal Detalhes Contato
            </div>
          </div>
    </div>
</div>
</div>
