
<br><br><br><br>
<div class="col-xs-12">
    <div class="col-lg-3">
        <div class="sidebar-flat-perfil label-primary col-xs-12 padding-zero">
            <br>
            <div class="emulate-img label-default center-block img-circle"></div>
            <br>
            <li class="list-group-item" data-toggle="collapse" href="#perfilcollapse" aria-expanded="false" aria-controls="perfilcollapse"><b>Perfil <i class="caret"></i></b></li>
            <ul class="list-group list-flat in" id="perfilcollapse" data-toggle="collapse">
                <li class="list-group-item"><span class="glyphicon glyphicon-user"></span> Insituição lar dos meninos</li>
                <li class="list-group-item"><span class="glyphicon glyphicon-user"></span></li>
            </ul>
        </div>
    </div>
    <div class="col-lg-5">
        <div class=" col-xs-12 padding-zero label-default">
            <i></i>
            <li class="list-group-item">
                <b>Donativos</b>
                <a class="btn btn-xs btn-success pull-right"><span class="glyphicon glyphicon-plus"></span></a>
            </li>
            <?php echo $listaDonativos;?>
        </div>
    </div>
    <div class="col-lg-4">
        <div class="col-sx-12 padding-zero label-success">
            <i></i>
            <li class="list-group-item">
                <b>Doadores Recentes</b>
            </li>
            <li class="list-group-item">
                <b>Quantidade: <span class="badge" title="Quantidade doada">12</span>
                    <a class="btn btn-xs btn-primary pull-right">Recebido <i class="glyphicon glyphicon-ok"></i></a></b>
            </li>
            <ul class="list-flat list-group">
                <li class="list-group-item">
                    Hebert Alves da Silva <br>
                    <sub>Data doação: 24/04/2015</sub>
                    <sub>Expira em: 24/05/2015</sub>
                </li>
            </ul>
            <li class="list-group-item">
                <b>Quantidade: <span class="badge" title="Quantidade doada">12</span>
                    <a class="btn btn-xs btn-primary pull-right">Recebido <i class="glyphicon glyphicon-ok"></i></a></b>
            </li>
            <ul class="list-flat list-group">
                <li class="list-group-item">
                    Albos Borges <br>
                    <sub>Data doação: 24/04/2015</sub>
                    <sub>Expira em: 24/05/2015</sub>
                </li>
            </ul>
            <li class="list-group-item">
                <b>Quantidade: <span class="badge" title="Quantidade doada">12</span>
                    <a class="btn btn-xs btn-primary pull-right">Recebido <i class="glyphicon glyphicon-ok"></i></a></b>
            </li>
            <ul class="list-flat list-group">
                <li class="list-group-item">
                    Wesley Fernando <br>
                    <sub>Data doação: 24/04/2015</sub>
                    <sub>Expira em: 24/05/2015</sub>
                </li>
            </ul>
        </div>
    </div>
</div>
