<div class='row-fluid'>
    <div class="col-xs-12">
        <form id="pesquisar" class="navbar-form pull-left" method="get">
            <div class="input-group" style="max-width:470px;">
                <input type="text" class="form-control" placeholder="Pesquisar" name="buscaPesquisa" id="buscaPesquisa" >
                <div class="input-group-btn">
                    <button class="btn btn-default btn-primary" id="btnPesquisar" type="submit"><i class="glyphicon glyphicon-search"></i></button>
                </div>
            </div>
        </form>
    </div>
</div>

<div class="row-fluid">
<?php
   $eventos = $this->eventos;
    foreach($eventos as $evento){
        echo "<div class='col-sm-6 col-md-4'>";
        echo "<h2 class='page-header text-info text-center'>{$evento['nomeFantasia']}</h2>";
        echo "<div class='thumbnail'>";
        echo "<img class='img img-responsive' src='{$evento['imagem1']}' alt='...' >";
        echo "<div class='caption'>
                <h3></h3>
                <p>{$evento['descEvento']}</p>
                <p><a href='#' class='btn btn-primary' role='button'>Compartilhar</a> <a href='#' class='btn btn-default' role='button'>Doar</a></p>
              </div>
             </div>
             </div>
            ";
    }
    //var_dump($this->eventos);
?>
