<div class='row-fluid'>
    <div class="col-xs-12">
        <form id="pesquisar" class="navbar-form pull-left" method="get">
            <div class="input-group" style="max-width:470px;">
                <input type="text" class="form-control" placeholder="Pesquisar" name="buscaPesquisa" id="buscaPesquisa" >
                <div class="input-group-btn">
                    <button class="btn btn-default btn-primary" id="btnPesquisar" type="submit"><i class="glyphicon glyphicon-search"></i></button>

                </div>
            </div>
        </form>
    </div>
</div>

<div class="row-fluid">
    <div class="col-sm-6 col-md-4">
        <h2 class="page-header text-info text-center">Apae</h2>
        <div class="thumbnail">
                <img class="img img-responsive" src="/img/data/eventos/testedoa.jpg" alt="..." >
            <div class="caption">
                <h3></h3>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                    Praesent interdum nisi at neque fermentum tempor
                    efficitur nisl, non ultricies justo odio lobortis nisl. Donec pretium turpis vitae orci malesuada tempor. Nunc ac vestibulum velit. Vivamus commodo lorem nibh, .</p>
                <p><a href="#" class="btn btn-primary" role="button">Compartilhar</a> <a href="#" class="btn btn-default" role="button">Doar</a></p>
            </div>
        </div>
    </div>
    <div class="col-sm-6 col-md-4">
        <h2 class="page-header text-info text-center">Instituto</h2>
        <div class="thumbnail">
            <img class="img img-responsive" src="/img/data/eventos/doe.jpg" alt="...">
            <div class="caption">
                <h3></h3>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                    Praesent interdum nisi at neque fermentum tempor
                    efficitur nisl, non ultricies justo odio lobortis nisl. Donec pretium turpis vitae orci malesuada tempor. Nunc ac vestibulum velit. Vivamus commodo lorem nibh, .</p>
                <p><a href="#" class="btn btn-primary" role="button">Compartilhar</a> <a href="#" class="btn btn-default" role="button">Doar</a></p>
            </div>
        </div>
    </div>
    <div class="col-sm-6 col-md-4">
        <h2 class="page-header text-info text-center">São João</h2>
        <div class="thumbnail">
            <img src="/img/data/eventos/agasalho.jpg" alt="..." >
            <div class="caption">
                <h3></h3>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                    Praesent interdum nisi at neque fermentum tempor
                    efficitur nisl, non ultricies justo odio lobortis nisl. Donec pretium turpis vitae orci malesuada tempor. Nunc ac vestibulum velit. Vivamus commodo lorem nibh, .</p>
                <p><a href="#" class="btn btn-primary" role="button">Compartilhar</a> <a href="#" class="btn btn-default" role="button">Doar</a></p>
            </div>
        </div>
    </div>
</div>
