<style>
    .imagem-evento{
        width: 400px !important;
        height: 200px !important;
    }
</style>

<div class='row-fluid'>
    <div class="col-xs-12">
        <form id="pesquisar" class="navbar-form pull-left" method="get">
            <div class="input-group" style="max-width:470px;">
                <input type="text" class="form-control" placeholder="Pesquisar" name="buscaPesquisa" id="buscaPesquisa" >
                <div class="input-group-btn">
                    <button class="btn btn-default btn-primary" id="btnPesquisar" type="submit"><i class="glyphicon glyphicon-search"></i></button>
                </div>
            </div>
        </form>
    </div>
</div>

<div class="row-fluid">
<?php
   $eventos = $this->eventos;
    foreach($eventos as $evento){
        echo "<div class='col-sm-6 col-md-4'>";
        echo "<div class='thumbnail'>";
        echo "<h3 class='text-center'><a class='text-info' href='#'>{$evento['tituloEvento']}</a></h3>";
        echo "<h4 class='text-center'><a class='text-success' href='#'>{$evento['nomeFantasia']}</a></h4>";
        echo "<img class='img img-responsive imagem-evento' src='{$evento['imagem1']}' alt='...' >";
        echo "<div class='caption'>
                <h3></h3>
                ";
        echo "<p><strong>Periodo:</strong> {$evento['dataInicio']->format('d/m/Y')} à {$evento['dataFim']->format('d/m/Y')}</p>";
        if(!empty($evento['siteEvento'])){
            echo "<p><strong>Site:</strong> <a target='_blank' href='http://{$evento['siteEvento']}'>{$evento['siteEvento']}</a></p>";
        }
        echo "<p><strong>Objetivos:</strong> {$evento['objetivos']}</p>
                <p>{$evento['descEvento']}</p>
                <p> <a href='#' class='btn btn-primary' role='button'>Compartilhar</a>
                    <a href='#' class='btn btn-default' role='button'>Doar</a></p>
              </div>
             </div>
             </div>
            ";
    }
?>
</div>