
<div class="grid padding10">
    <div class="row cells4">
        <div class="cell">
            <div class="tile-large bg-blue"">
                <div class="tile-content slide-left-2">
                    <div class="slide">
                        <div class="image-container">
                            <div class="frame">
                                <img src="<?php echo $dadosPessoa->getFoto() ?>" />
                            </div>
                        </div>
                    </div>

                    <div class="slide-over bg-darkRed">

                        <h3 class="padding10 fg-white">
                        <?php echo $dadosPessoa->getNome();
                        ?>
                        </h3>
                        <h3 class="padding10 fg-white">
                            <?php echo $dadosPessoa->getEmail();
                            ?>
                        </h3>
                        <h3 class="padding10 fg-white">
                            <a href="/pessoa/minha-conta" >Alterar Conta</a>
                        </h3>

                    </div>
                </div>
            </div>
            <div class="tile-small">
                <div class="tile-content iconic slide-left">
                    <div class="slide">
                        <span class="icon mif-shopping-basket"></span>
                    </div>
                    <div class="slide-over">
                        <span>Doações Pendentes</span>
                        <span class="tile-badge"><?php echo $this->quantTransacoes['pendente'] ?></span>
                    </div>
                </div>
            </div>
            <div class="tile-small">
                <div class="tile-content iconic slide-left">
                    <div class="slide">
                        <span class="icon mif-chart-line"></span>
                    </div>
                    <div class="slide-over">
                        <span>Doações Feitas</span>
                        <span class="tile-badge"><?php echo $this->quantTransacoes['finalizado'] ?></span>
                    </div>
                </div>
            </div>
            <div class="tile-small">
                <div class="tile-content iconic slide-left">
                    <div class="slide">
                        <span class="icon mif-chart-line"></span>
                    </div>
                    <div class="slide-over">
                        <span>Minhas Instituições</span>
                        <span class="tile-badge"><?php echo $this->quantMinhasInstituicoes ?></span>
                    </div>
                </div>
            </div>


        </div>
        <div class="cell colspan2">
            <?php
            if($transacoesPendentes){
                foreach($transacoesPendentes as $transacaoPendente){
                    if($transacaoPendente instanceof \Application\Entity\Transacao){
                        echo '<div class="tile-large bg-grayLighter">';
                        echo '<div class="tile-contente padding10">';
                        echo "<a href='pessoa/instituicao-page?id={$transacaoPendente->getInstituicao()->getId()}'><h5><img class='foto-perfil-feed img' src={$transacaoPendente->getInstituicao()->getFoto()} /><strong> Instituicao {$transacaoPendente->getInstituicao()->getNomeFantasia()} - <span class='text-success'>Doação:{$transacaoPendente->getDonativo()->getTitulo()}</span></strong></h5></a>";
                        echo "<p>{$transacaoPendente->getDonativo()->getDescricao()}</p>";
                        echo "<p>Qtd:{$transacaoPendente->getDonativo()->getQuantidade()}</p>";
                        echo "<p>Você doou em :{$transacaoPendente->getDataTransacao()->format('d/m/Y')}</p>";
                        echo "<p class='text-danger'>* Aguarde finalização da doação pela instituicao</p>";
                        echo '<a id="ver-historico" href="#" style="margin-bottom: 10px"><i class="glyphicon glyphicon-envelope"></i> Ver histórico</a>';
                        echo '<div class="historico ocultar">';
                        echo 'aqui vai o historico';
                        echo '</div>';
                        echo '</div>';

                        echo '</div>';

                    }
                }
            }
            ?>
        </div>
        <div class="cell">
            <?php
            if(!is_array($this->campanhas)){
                echo '<div class="tile-wide bg-red fg-white"><div class="tile-content padding10">'.$this->campanhas.'</div></div>';
            }else{
                foreach($campanhas as $campanha){
                    echo "<div class='tile-wide bg-amber'>";
                    echo "<div class='tile-content'>";
                    echo "<strong>Titulo:</strong> ".$campanha['tituloEvento'] . '<br>';
                    echo "<strong>Instituicao:</strong> ".$campanha['nomeFantasia'] . '<br>';
                    echo "<strong>Fim do evento:</strong> ".$campanha['dataFim'] . '<br>';
                    echo "<a style='margin-top: 4%' class='btn btn-default btn-sm' href='/evento/evento-page?id={$campanha['id']}'>Ver Mais</a>";
                    echo "</div>";
                    echo "</div>";
                }
            }
            ?>
        </div>
    </div>
</div>

<script src="/js/doacao/pessoaPrincipal.js"></script>
<script src="/js/doacao/pessoaInstituicao.js"></script>
