<div class="row-fluid">
    <div class="col-xs-3">
        <div class="well">
            <?php

            if($this->dadosPessoa){
                $dadosPessoa = $this->dadosPessoa;
                echo "<img class='img img-responsive' style='width:280px' src='".$dadosPessoa->getFoto(). "' /><br>";
                echo "<strong class='text-info'>".$dadosPessoa->getNome().'</strong><br>';
                echo $dadosPessoa->getEmail().'<br>';
                echo '<a class="btn-link" href="/pessoa/minha-conta">Editar Perfil</a>';
            }else{
                echo "<img class='img img-responsive' style='width:280px' src='/img/data/sem-foto.jpg' /><br>";
            }
            ?>
        </div>
    </div>

</div>

<!-- Colocar $this->formDivulgacao aqui-->
<div class="row-fluid">
    <div class="col-xs-5">
        <div class="row">
            <div class="container col-xs-12">
                <div id="conteudo-atualizacao">

                    <div class="container-doacoes">
                    <h3 class="down-doacao text-info" style="cursor: pointer"><i class="glyphicon glyphicon-minus"></i> Doações</h3>
                        <div class="doacoes div-slide down">
                        <?php
                            if($transacoes){
                                foreach($transacoes as $transacao){
                                    if($transacao instanceof \Application\Entity\Transacao){
                                            echo '<div class="well">';
                                            echo "<a href='pessoa/instituicao-page?id={$transacao->getInstituicao()->getId()}'><h5><img class='foto-perfil-feed img' src={$transacao->getInstituicao()->getFoto()} /><strong> Instituicao {$transacao->getInstituicao()->getNomeFantasia()} - <span class='text-success'>Doação:{$transacao->getDonativo()->getTitulo()}</span></strong></h5></a>";
                                            echo "<p>{$transacao->getDonativo()->getDescricao()}</p>";
                                            echo "<p>Qtd:{$transacao->getDonativo()->getQuantidade()}</p>";
                                            echo "<p>Você doou em :{$transacao->getDataTransacao()->format('d/m/Y')}</p>";
                                            echo "<p class='text-danger'>* Aguarde finalização da doação pela instituicao</p>";
                                            echo '<a id="ver-historico" href="#" style="margin-bottom: 10px"><i class="glyphicon glyphicon-envelope"></i> Ver histórico</a>';
                                            echo '<div class="historico ocultar">';
                                            echo 'aqui vai o historico';
                                            echo '</div>';

                                            echo '</div>';
                                    }
                                }
                            }
                        ?>
                        </div>
                    </div>

                    </div>

                </div>
            </div>
        </div>
    </div>

    <div class="col-xs-4">
        <div class="container-eventos">
            <h3 class="down-evento text-info" style="cursor: pointer"><i class="glyphicon glyphicon-minus"></i>Eventos</h3>
            <div class="eventos div-slide down">
                <div class="well">
                    <?php
                    if(!is_array($this->campanhas)){
                        echo $this->campanhas;
                    }else{
                        foreach($campanhas as $campanha){
                            echo "<div class='well text-capitalize'>";
                            echo "<strong>Titulo:</strong> ".$campanha['tituloEvento'] . '<br>';
                            echo "<strong>Instituicao:</strong> ".$campanha['nomeFantasia'] . '<br>';
                            echo "<strong>Fim do evento:</strong> ".$campanha['dataFim'] . '<br>';
                            echo "<a style='margin-top: 4%' class='btn btn-default btn-sm' href='/evento/evento-page?id={$campanha['id']}'>Ver Mais</a>";
                            echo "</div>";
                        }
                    }
                    ?>
                </div>
            </div>
    </div>
</div>

<script src="/js/doacao/pessoaPrincipal.js"></script>
<script src="/js/doacao/pessoaInstituicao.js"></script>
<script>

    /*
    principal.facebook('post');
    //divulgacao-form
    $(document).ready(function () {
        $('#divulgacao-form').submit(function (e) {
            e.preventDefault();

            $.ajax({
                data: $('#divulgacao-form').serialize(),
                type: 'POST',
                url:'/evento/publicar',
                success: function (data) {

                }
            });

        });
    });

        $('#btnPublicar').click(function () {
            FB.ui(
                {
                    method: 'feed',
                    link: 'https://developers.facebook.com/docs/',
                    caption: 'An example caption'
                },
                // callback
                function(response) {
                    if (response && !response.error_code) {
                        alert('Posting completed.');
                    } else {
                        alert('Error while posting.');
                    }
                }
            );
        });

        */

</script>