<div class="grid">
    <div class="row cell">
        <div class="cell padding20">
            <form id="pesquisar" method="get">
                <div class="input-control text" data-role="input" style="max-width:470px;">
                    <input type="text" placeholder="Pesquisar" name="buscaPesquisa" id="buscaPesquisa">
                    <button class="button primary" id="btnPesquisar" type="submit"><span class="mif-search"></span></button>
                </div>
                <label class="input-control radio small-check">
                    <input type="radio" name="filtro" value="minhas" id="minhas"/>
                    <span class="check"></span>
                    <span class="caption">Minhas Instituições</span>
                </label>
                <label class="input-control radio small-check">
                    <input type="radio" name="filtro" value="todos" id="todos" />
                    <span class="check"></span>
                    <span class="caption">Instituições para seguir</span>
                </label>
            </form>
        </div>
    </div>
    <div class="row cell">
        <div class="cell" id="containerInstituicao">
            <?php
            if($instituicoes){
            foreach($instituicoes as $instituicao){
            echo "
            <div class='tile-large bg-darkblue'>
                <div class='tile-content slide-left-2'>
                    <div class='slide'>
                    <form class='formSeguir' method='post'>
                    <input class='instituicaoID' type='hidden' name='id' value='".$instituicao['id'] ."'>
                    <div class='panel panel-default'>
                        <div class='panel-heading'><a href='/pessoa/instituicao-page?id={$instituicao['id']}' class='pull-right'>Ver mais</a> <h4>". $instituicao['nomeFantasia']."</h4></div>
                        <div class='panel-body'>
                            <p>" . $instituicao['descricao'] ."<img src={$instituicao['foto']} class='img-circle pull-right img-profile'> <a href='#'></a></p>
                            <div class='clearfix'></div>
                            <hr>
                            <input type='button' class='btn btn-primary btn-seguir' value='Seguir'>
                        </div>
                    </div>
                </form>
                    </div>
                    <div class='slide-over'>

                    </div>
                </div>
            </div>"
            ;
            }
            }
            else{
            echo '<div class="container">';
                echo "<strong>Sem instituicções para seguir</strong><br>";
                echo '</div>';
            }
            ?>
        </div>
    </div>
</div>
<!--Inicio Instituicao -->
<!--Fim Instituicao -->

<script src="/js/doacao/pessoaInstituicao.js"></script>
