<div class="row-fluid">

    <div class="col-md-4 col-sm-6">

        <div class="panel panel-default">
            <div class="panel-heading"><a href="#" class="pull-right">Ver mais</a> <h4>APAE</h4></div>
            <div class="panel-body">
                <p><img src="//placehold.it/150x150" class="img-circle pull-right"> <a href="#">Publicidade</a></p>
                <div class="clearfix"></div>
                <hr>
                Descricao instituicao
            </div>
        </div>

    </div>

    <div class="col-md-4 col-sm-6">

        <div class="panel panel-default">
            <div class="panel-heading"><a href="#" class="pull-right">Ver mais</a> <h4>São Cristovão</h4></div>
            <div class="panel-body">
                <p><img src="//placehold.it/150x150" class="img-circle pull-right"> <a href="#">São Cristovão</a></p>
                <div class="clearfix"></div>
                <hr>
                Descricao instituicao
            </div>
        </div>

    </div>

    <div class="col-md-4 col-sm-6">

        <div class="panel panel-default">
            <div class="panel-heading"><a href="#" class="pull-right">Ver mais</a> <h4>Instituicao</h4></div>
            <div class="panel-body">
                <p><img src="//placehold.it/150x150" class="img-circle pull-right"> <a href="#">Instituicao</a></p>
                <div class="clearfix"></div>
                <hr>
                Descricao instituicao
            </div>
        </div>

    </div>

</div>


<div class="row-fluid">

    <div class="col-md-4 col-sm-6">

        <div class="panel panel-default">
            <div class="panel-heading"><a href="#" class="pull-right">Ver mais</a> <h4>Fome Zero</h4></div>
            <div class="panel-body">
                <p><img src="//placehold.it/150x150" class="img-circle pull-right"> <a href="#">Fome Zero</a></p>
                <div class="clearfix"></div>
                <hr>
                Descricao instituicao
            </div>
        </div>

    </div>

    <div class="col-md-4 col-sm-6">

        <div class="panel panel-default">
            <div class="panel-heading"><a href="#" class="pull-right">Ver mais</a> <h4>Outra</h4></div>
            <div class="panel-body">
                <p><img src="//placehold.it/150x150" class="img-circle pull-right"> <a href="#">Outra</a></p>
                <div class="clearfix"></div>
                <hr>
                Descricao instituicao
            </div>
        </div>

    </div>

    <div class="col-md-4 col-sm-6">

        <div class="panel panel-default">
            <div class="panel-heading"><a href="#" class="pull-right">Ver mais</a> <h4>RARA</h4></div>
            <div class="panel-body">
                <p><img src="//placehold.it/150x150" class="img-circle pull-right"> <a href="#">RAra</a></p>
                <div class="clearfix"></div>
                <hr>
                Descricao instituicao
            </div>
        </div>

    </div>

</div>