<?php
$instituicao = $this->instituicao;
?>

<style>
    .foto{
        width: 140px;
        height: 140px;
    }
    .img-local-inst{
        width: 200px;
        height: 200px;
        outline: 1px solid #222222;
        box-shadow: 1px 2px 3px #ccc;
    }
</style>


<div class="col-xs-12">
    <div class="row">
        <div class="col-xs-2">
            <img class="img foto img-circle" src="<?php echo $instituicao->getFoto()?>" />
            <div><strong>Nome Fantasia: </strong><?php echo $instituicao->getNomeFantasia() ?></div>
            <div><strong>Email: </strong><?php echo $instituicao->getEmail() ?></div>
            <div><strong>Site: </strong><a href="<?php echo $instituicao->getSite()?>"><?php echo $instituicao->getSite()?></a></div>
            <div><strong>CNPJ: </strong><?php echo $instituicao->getCnpj() ?></div>
        </div>

        <div class="col-xs-6">
            <h4>Bem vindo a página da instituicao <?php echo $instituicao->getNomeFantasia() ?></h4>
            <p><?php echo $instituicao->getDescricao() ?></p>
            <div class="">
                <?php
                    foreach($instituicao->getFotosLocal() as $key=>$linkFoto){
                        echo "<img src='{$linkFoto}' class='img img-local-inst' />";
                    }
                ?>
            </div>
        </div>

        <!-- vai virar html no script -->
        <div class="col-sm-4" style="padding-left: 30px;padding-bottom: 20px;">
            <h4>Oferecer Produtos</h4>
            <p>Você pode oferecer produtos para a instituicao.</p>
            <button class="btn btn-success" id="btn-oferecer">Oferecer Doação</button>
        </div>

        <!-- vai virar html no script -->
        <div id="donativoConteudo" class="col-sm-4">

        </div>

        <div id="doacaoModal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                        <h2 class="text-center">Confirmar Doacao</h2>
                    </div>
                    <div class="modal-body">

                    </div>

                </div>

            </div>
        </div>
    </div>
</div>


<script src="/js/doacao/pessoaInstituicao.js"></script>
