<?php
$instituicao = $this->instituicao;
?>

<style>
    .foto{
        width: 140px;
        height: 140px;
    }
    .img-local-inst{
        width: 200px;
        height: 200px;
        outline: 1px solid #222222;
        box-shadow: 1px 2px 3px #ccc;
    }
</style>


<div class="col-xs-12">
    <div class="row">
        <div class="col-xs-2">
            <img class="img foto img-circle" src="<?php echo $instituicao->getFoto()?>" />
            <div><strong>Nome Fantasia: </strong><?php echo $instituicao->getNomeFantasia() ?></div>
            <div><strong>Email: </strong><?php echo $instituicao->getEmail() ?></div>
            <div><strong>Site: </strong><a href="<?php echo $instituicao->getSite()?>"><?php echo $instituicao->getSite()?></a></div>
            <div><strong>CNPJ: </strong><?php echo $instituicao->getCnpj() ?></div>
        </div>

        <div class="col-xs-6">
            <h4>Bem vindo a página da instituicao <?php echo $instituicao->getNomeFantasia() ?></h4>
            <p><?php echo $instituicao->getDescricao() ?></p>
            <div class="">
                <?php
                    foreach($instituicao->getFotosLocal() as $key=>$linkFoto){
                        echo "<img src='{$linkFoto}' class='img img-local-inst' />";
                    }
                ?>
            </div>
        </div>

        <!-- vai virar html no script -->
        <div id="donativoConteudo" class="col-sm-4">

        </div>

    </div>
</div>


<script src="/js/doacao/pessoaInstituicao.js"></script>