<style>
    .sidebar {
        position: fixed;
        top: 91px;
        bottom: 0;
        left: 0;
        z-index: 1000;
        display: block;
        padding: 20px;
        overflow-x: hidden;
        overflow-y: auto; /* Scrollable contents if viewport is shorter than content. */
        background-color: #f5f5f5;
        border-right: 1px solid #eee;
    }
</style>
<div class="row">
    <div class="col-xs-12">
        <div class="col-xs-3 sidebar">
            <ul class="nav nav-sidebar">
                <li id="dadosPessoa" class="active"><a href="#"><i class="glyphicon glyphicon glyphicon-edit"></i> Editar Meus Dados</a></li>
                <li id="alteraSenha"><a href="#"><i class="glyphicon glyphicon glyphicon-lock"></i> Alterar Senha</a></li>
                <li id="alteraPreferencias"><a href="#"><i class="glyphicon glyphicon glyphicon-cog"></i> Editar Preferências</a></li>
                <li id="cancelarConta"><a href="#"><i class="glyphicon glyphicon glyphicon-trash"></i> Cancelar Conta</a></li>
            </ul>
        </div>

        <div id="conteudo" class="col-xs-9" style="float: right;">

        </div>
    </div>
</div>

<script src="/js/doacao/pessoaMinhaConta.js"></script>