<?php
if($this->pageCount){
    echo "<div class='paginationControl'>";
    if (isset($this->previous)){
        echo '<a href="' . $this->url($this->route, array('page' => $this->previous)) . '"> &lt; Anterior
        </a> ';
    }
    else{
        echo "<span class='disabled'>&lt; Anterior</span> |";
    }

    foreach($this->pagesInRange as $page){
        if ($page != $this->current){
            echo '<a href="' . $this->url($this->route, array('page' => $page)) . '">'.
            $page . '|</a> ';
        }
        else{
            echo $page . '|';
        }
    }

    if (isset($this->next)){
        echo '<a href="' . $this->url($this->route, array('page' => $this->next)) . '">  Próximo &gt;
        </a> ';
    }
    else{
        echo "<span class='disabled'>Próximo &gt;</span> |";
    }
}


?>
