<?php
$title= 'Cadastro de Usuario';
$this->headTitle($title);
?>
<?php
$form = $this->form;
$form->setAttribute('action', $this->urlAction);
$form->prepare();
?>

<div class="row">
    <h1><?=$this->escapeHtml($title) ?></h1>
    <?php
    //exibe os itens em arvore, para realibitar é necessario alterar em global.php
    //=$this->navigation('Navigation')->menu()?>
</div>
<div class="row">
    <div class="col-sm-4">
        <?=$this->form()->openTag($form)?>

        <?=$this->formLabel($form->get('lbllogin'));?>
        <?=$this->formRow($form->get('login'))?>

        <?=$this->formLabel($form->get('lblPass'));?>
        <?=$this->formRow($form->get('senha'))?>

        <?=$this->formLabel($form->get('lblPassConfirma'));?>
        <?=$this->formRow($form->get('confirmarsenha'))?>

        <br>
        <?=$this->formRow($form->get('cadastrar'))?>


        <?=$this->messages?>

        <?=$this->form()->closeTag()?>
    </div>
</div>