
<style>
    body{
        background-color: #fff;
    }
</style>

    <!-- inicio Banner-->

<div id="myCarousel" class="carousel slide">
    <ol class="carousel-indicators" style="list-style: none;">
        <li class="active" data-target="#myCarousel" data-slide-to="0"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>

    <!-- Carousel Form e itens-->
    <div class="carousel-inner" style="z-index:1">
        <div id="inside-carousel" class="container-flid centralizado">
            <div class="carousel-caption" style="bottom: 42%;padding-top:0;padding-bottom:0">
                <div class="row">

                </div>
            </div>
        </div>
        <div class="active item"><!-- Imagens do banner-->
            <img src="/img/pessoa3.jpg" alt="imagetext 1" />
        </div>
        <div class="item">
            <img src="/img/pessoa.jpg"  alt="imagetext 2" />
        </div>
        <div class="item">
            <img src="/img/pessoa3.jpg" alt="imagetext 3" />
        </div>
    </div>
</div><!-- fim Banner-->

<div class="container">
    <div class="row">
        <div class="col-lg-4">
            <h2 class="text-center">Heading</h2>
            <p>Donec sed odio dui. Etiam porta sem malesuada magna mollis euismod. Nullam id dolor id nibh ultricies vehicula ut id elit. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Praesent commodo cursus magna.</p>
            <p><a class="btn btn-default" href="#" role="button">View details »</a></p>
        </div>
        <div class="col-lg-4">
            <h2 class="text-center">Heading</h2>
            <p>Donec sed odio dui. Etiam porta sem malesuada magna mollis euismod. Nullam id dolor id nibh ultricies vehicula ut id elit. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Praesent commodo cursus magna.</p>
            <p><a class="btn btn-default" href="#" role="button">View details »</a></p>
        </div>
        <div class="col-lg-4">
            <h2 class="text-center">Heading</h2>
            <p>Donec sed odio dui. Etiam porta sem malesuada magna mollis euismod. Nullam id dolor id nibh ultricies vehicula ut id elit. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Praesent commodo cursus magna.</p>
            <p><a class="btn btn-default" href="#" role="button">View details »</a></p>
        </div>
    </div>
</div>


<script>
    $(document).ready(function(e) {
        $('.carousel').carousel({
            interval: 4000
        });
    });
</script>