
<?php
$this->layout()->setTemplate('layout/layout_modal.phtml');

$form = $this->loginForm;
$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/login'));
$form->setAttribute('method', 'post');
$form->setAttribute('class', 'form-signin');

?>
        <?php echo $this->form()->openTag($form) ?>
        <div class="input-control modern text iconic">
            <?php echo $this->formInput($form->get('identity')) ?>
            <span class="label">E-mail</span>
            <span class="informer">E-mail cadastrado</span>
            <span class="placeholder">Entre com seu e-mail</span>
            <span class="icon mif-user"></span>
        </div>
        <div class="input-control modern password iconic">
            <?php echo $this->formInput($form->get('credential')) ?>
            <span class="label">Senha</span>
            <span class="informer">Digite sua senha</span>
            <span class="placeholder">Sua senha</span>
            <span class="icon mif-lock"></span>
        </div>

        <h4>
            <label class="switch">
                Me lembre
                <input type="checkbox" value="lembrar" id="lembrar">
                <span class="check"></span>
            </label>
        </h4>
        <?php echo $this->formElementErrors($form->get('identity')) ?>

    <?php if ($this->redirect): ?>
        <input type="hidden" name="redirect" value="<?php echo $this->escapeHtml($this->redirect) ?>" />
    <?php endif ?>
    <h4>
        <?php echo $this->formButton($form->get('submit')->setAttribute('class','button success small-button')) ?>
    </h4>
<?php echo $this->form()->closeTag() ?>

