<?php echo $this->doctype(); ?>
<html lang="pt-br">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/flat-style.css')
                        ->prependStylesheet($this->basePath() . '/css/metro.css')
                        ->prependStylesheet($this->basePath() . '/css/metro-icons.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-modal.css')
                        //->prependStylesheet($this->basePath() . '/css/jquery-ui.css')
                        //->prependStylesheet($this->basePath() . '/css/jquery-ui.structure.css')
                        //->prependStylesheet($this->basePath() . '/css/jquery-ui.theme.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            //->prependFile($this->basePath() . '/js/doacao/doacao.js')
            ->prependFile($this->basePath() . '/js/doacao/instituicao.js')
            //->prependFile($this->basePath() . '/js/jquery-ui.js')
            ->prependFile($this->basePath() . '/js/metro.js')
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '//ajax.googleapis.com/ajax/libs/jquery/2.0.2/jquery.min.js')
            ->prependFile($this->basePath() . '/js/jquery.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ;
        ?>

    </head>
    <body>
    <header class="app-bar fixed-top" data-role="appbar" data-flexstyle="sidebar2">
        <div>
            <a href="#" class="app-bar-element branding">
                <img src="/img/logo.png" class="logo"/>
            </a>
            <ul class="app-bar-menu">
                <li><a href="<?php echo $this->url('instituicao',array('action'=>'index'));?>">Painel</a></li>
                <li><a href="<?php echo $this->url('transacao'); ?>">Recebidos</a></li>
                <li><a href="#loginModal">Eventos</a></li>
                <li><a href="<?php echo $this->url('donativo');?>">Gerenciar</a></li>
                <li><a href="#aboutModal">Denunciar Abusos</a></li>
            </ul>
            <div class="app-bar-element place-right">
                <a href="/user/logout" title="Sair"><span class="mif-exit fg-white"></span></a>
            </div>
        </div>
            <!-- ul class="btn-group btn-group-lg pull-right">
                <li class="btn">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="glyphicon glyphicon-bell"></i></a>
                    <ul class="dropdown-menu">
                        <li><a href="#"><span class="badge pull-right">40</span>Link</a></li>
                        <li><a href="#"><span class="badge pull-right">2</span>Link</a></li>
                        <li><a href="#"><span class="badge pull-right">0</span>Link</a></li>
                        <li><a href="#"><span class="label label-info pull-right">1</span>Link</a></li>
                        <li><a href="#"><span class="badge pull-right">13</span>Link</a></li>
                    </ul>
                </li>
                <li class="btn"><a href="#" id="btnToggle"><i class="glyphicon glyphicon-th-large"></i></a></li>
                <li class="btn"><a href="\application\index\logout"><i class="glyphicon glyphicon-user"></i></a></li>
                <li class="btn navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse1">
                    <i class="glyphicon glyphicon-search"></i>
                </li>
                <li class="btn navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse2">
                    <span class="sr-only">Toggle navigation</span>
                    <i class="glyphicon glyphicon-list"></i>
                </li>
            </ul-->
    </header>

    <div class="grid" id="main">
            <?php echo $this->content; ?>
    </div> <!-- /container -->
        <footer>
            <div class="col-xs-12 text-center">
            	<p><a href="http://www.bootply.com/download/90113" target="_ext">Colocar redes sociais aqui</a></p>
            </div>
        </footer>
    <div class="modal fade" id="modal-item">
        <div class="modal-dialog">
            <div class="modal-content bg-grayLighter">
                <div class="modal-body"></div>
            </div>
        </div>
    </div>
    </body>
</html>
