<?php echo $this->doctype(); ?>

<html lang="pt-br">
    <head>
        <meta charset="utf-8">

        <?php
        echo $this->headTitle('Sistema Doacao')->setSeparator(' - ')->setAutoEscape(false);
        echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/styles.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.css')
                        ->prependStylesheet($this->basePath() . '/css/jquery-ui.css')
                        ->prependStylesheet($this->basePath() . '/css/jquery-ui.structure.css')
                        ->prependStylesheet($this->basePath() . '/css/jquery-ui.theme.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/doacao/doacao.js')
            ->prependFile($this->basePath() . '/js/bootbox/bootbox.js')
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery-ui.js')
            ->prependFile($this->basePath() . '/js/jquery.js')
            //->prependFile($this->basePath() . '/js/scripts.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>

    <nav class="navbar navbar-fixed-top header">
        <div class="col-md-12">
            <div class="navbar-header">

                <a href="/pessoa" class="padrao-header"><img style="height:40px;margin-top: 5px" src="/img/logo.png" /></a>
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse1">
                    <i class="glyphicon glyphicon-search"></i>
                </button>

            </div>
            <div class="collapse navbar-collapse" id="navbar-collapse1">
                <form class="navbar-form pull-left">
                    <div class="input-group" style="max-width:470px;">
                        <input type="text" class="form-control" placeholder="Pesquisar" name="busca-generica" id="busca-generica">
                        <div class="input-group-btn">
                            <button class="btn btn-default btn-primary" type="submit"><i class="glyphicon glyphicon-search"></i></button>
                        </div>
                    </div>
                </form>

                <?php
                $uri = $_SERVER['REQUEST_URI'];
                ?>

                <ul class="nav navbar-nav navbar-right">
                    <li style="line-height: 50px;padding-right: 10px"><span><a class="link-layout" href="/pessoa/minha-conta" style="text-decoration: none;color: #fff;text-shadow: 1px 1px 2px #000">Bem Vindo <?php echo $this->zfcUserDisplayName()?></a></span></li>
                    <!--<li><a class="" href="/" title="Notificações"><i class="glyphicon glyphicon-globe"></i></a></li>-->
                    <li>
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="glyphicon glyphicon-globe"></i></a>
                        <ul class="dropdown-menu">
                            <li><a href="#"><span class="badge pull-right">40</span>Link</a></li>
                            <li><a href="#"><span class="badge pull-right">2</span>Link</a></li>
                            <li><a href="#"><span class="badge pull-right">0</span>Link</a></li>
                            <li><a href="#"><span class="label label-info pull-right">1</span>Link</a></li>
                            <li><a href="#"><span class="badge pull-right">13</span>Link</a></li>
                        </ul>
                    </li>
                    <li><a class="<?php echo  $uri == '/pessoa' ? 'ativo' : '' ?>" href="/pessoa" title="Inicio"><i class="glyphicon glyphicon-home"></i></a></li>
                    <li><a class="<?php echo  $uri == '/pessoa/instituicao' ? 'ativo' : '' ?>" href="/pessoa/instituicao" title="Instituicões"><i class="glyphicon glyphicon-transfer"></i></a></li>
                    <li><a class="<?php echo  $uri == '/evento' ? 'ativo' : '' ?>" href="/evento" title="Eventos"><i class="glyphicon glyphicon-th-large"></i></a></li>
                    <li>
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="glyphicon glyphicon-user"></i></a>
                        <ul class="dropdown-menu">
                            <li><a href="\pessoa\minha-conta"><i class="glyphicon glyphicon-cog"></i> Minha Conta</a></li>
                            <li><a href="\pessoa\denunciar-abuso"><i class="glyphicon glyphicon-bookmark"></i> Denunciar Abusos</a></li>
                            <li><a href="\user\logout"><i class="glyphicon glyphicon-log-out"></i> Sair</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container-fluid" id="main">
            <?php echo $this->content; ?>
        <footer>

            <hr>
            <div style="outline: 1px solid #ccc" class="col-md-12 text-center"><p><a href="http://www.bootply.com/download/90113" target="_ext">Colocar redes sociais aqui</a></p></div>
            <hr>
        </footer>

    </div> <!-- /container -->

    <div id="preloading">
        <div id="loading"></div>
    </div>

    </body>



</html>

<script>

</script>