<?php echo $this->doctype(); ?>

<html lang="pt-br">
    <head>
        <meta charset="utf-8">

        <?php
        echo $this->headTitle('Sistema Doacao')->setSeparator(' - ')->setAutoEscape(false);
        echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/styles.css')
                        //->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/metro.css')
                        ->prependStylesheet($this->basePath() . '/css/flat-style.css')
                        ->prependStylesheet($this->basePath() . '/css/metro-icons.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.css')
                        ->prependStylesheet($this->basePath() . '/css/jquery-ui.css')
                        //->prependStylesheet($this->basePath() . '/css/jquery-ui.structure.css')
                        //->prependStylesheet($this->basePath() . '/css/jquery-ui.theme.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/doacao/doacao.js')
            //->prependFile($this->basePath() . '/js/bootbox/bootbox.js')
            ->prependFile($this->basePath() . '/js/metro.js')
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery-ui.js')
            ->prependFile($this->basePath() . '/js/jquery.js')
            //->prependFile($this->basePath() . '/js/scripts.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
    <div class="app-bar fixed-top bg-darkRed" data-role="appbar" data-flexstyle="sidebar2">
        <a class="app-bar-element branding bg-darkRed" href="/">
            <img class="logo" src="/img/logo.png"/>
        </a>
        <a class="app-bar-element text-shadow" href="/pessoa/minha-conta">
            <h5>Bem Vindo <?php echo $this->zfcUserDisplayName()?></h5>
        </a>
        <ul class="app-bar-menu centraliza-componente">
            <li><a href="/"><span class="mif-home"></span> </a></li>
            <li><a href="/pessoa/gerencia-transacao"><span class="mif-event-available"></span> </a> </li>
            <li><a href="/pessoa/instituicao"><span class="mif-library"></span> </a> </li>
            <li><a href="/evento"><span class="mif-tab"></span> </a></li>
            <li>
                <a class="dropdown-toggle"><span class="mif-user"></span></a>
                <ul class="d-menu" data-role="dropdown">
                    <li><a href="/pessoa/minha-conta"><span class="mif-cog"></span> Minha Conta</a></li>
                    <li><a href="/pessoa/denunciar-abuso"><span class="mif-bookmark"></span> Denunciar Abusos</a></li>
                    <li><a href="/user/logout"><span class="mif-exit"></span> Sair</a></li>
                </ul>
            </li>
        </ul>
    </div>
    <div class="grid" id="main">
            <?php echo $this->content; ?>
        <footer>

            <hr>
            <div style="outline: 1px solid #ccc" class="col-md-12 text-center"><p><a href="http://www.bootply.com/download/90113" target="_ext">Colocar redes sociais aqui</a></p></div>
            <hr>
        </footer>

    </div> <!-- /container -->

    <div id="preloading">
        <div id="loading"></div>
    </div>

    </body>



</html>

<script>

</script>