<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php
        echo $this->headTitle('Sistema Doacao')->setSeparator(' - ')->setAutoEscape(false);
        echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/styles.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.css')
                        ->prependStylesheet($this->basePath() . '/css/jquery-ui.css')
                        ->prependStylesheet($this->basePath() . '/css/jquery-ui.structure.css')
                        ->prependStylesheet($this->basePath() . '/css/jquery-ui.theme.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/doacao/doacao.js')
            ->prependFile($this->basePath() . '/js/jquery-ui.js')
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.js')
            //->prependFile($this->basePath() . '/js/scripts.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
    <div id="spinner">
        <img src="/img/ajax-loader.gif" alt="Loading..."/>
    </div>
    <nav class="navbar navbar-fixed-top header">
        <div class="col-md-12">
            <div class="navbar-header">

                <a href="#" class="navbar-brand padrao-header">Doação</a>
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse1">
                    <i class="glyphicon glyphicon-search"></i>
                </button>

            </div>
            <div class="collapse navbar-collapse" id="navbar-collapse1">
                <form class="navbar-form pull-left">
                    <div class="input-group" style="max-width:470px;">
                        <input type="text" class="form-control" placeholder="Pesquisar" name="srch-term" id="srch-term">
                        <div class="input-group-btn">
                            <button class="btn btn-default btn-primary" type="submit"><i class="glyphicon glyphicon-search"></i></button>
                        </div>
                    </div>
                </form>
                <ul class="nav navbar-nav navbar-right">
                    <div class="pull-left" style="margin-right: 20px;"><span style="line-height: 50px;color: #fff;text-shadow: 1px 1px 2px #000">Bem Vindo <?php echo $this->zfcUserDisplayName()?></span></div>
                    <li>
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="glyphicon glyphicon-bell"></i></a>
                        <ul class="dropdown-menu">
                            <li><a href="#"><span class="badge pull-right">40</span>Link</a></li>
                            <li><a href="#"><span class="badge pull-right">2</span>Link</a></li>
                            <li><a href="#"><span class="badge pull-right">0</span>Link</a></li>
                            <li><a href="#"><span class="label label-info pull-right">1</span>Link</a></li>
                            <li><a href="#"><span class="badge pull-right">13</span>Link</a></li>
                        </ul>
                    </li>
                    <li><a href="#" id="btnToggle"><i class="glyphicon glyphicon-th-large"></i></a></li>

                    <li>
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="glyphicon glyphicon-user"></i></a>
                        <ul class="dropdown-menu">
                            <li><a href="#">Minha Conta</a></li>
                            <li><a href="\user\logout">Sair</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>

    <div class="navbar navbar-default" id="subnav">
        <div class="col-md-12">
            <div class="navbar-header">

                <a href="#" style="margin-left:15px;" class="navbar-btn btn btn-default btn-plus dropdown-toggle" data-toggle="dropdown"><i class="glyphicon glyphicon-home" style="color:#dd1111;"></i> Inicio<small><i class="glyphicon glyphicon-chevron-down"></i></small></a>
                <ul class="nav dropdown-menu">
                    <li><a href="#"><i class="glyphicon glyphicon-user" style="color:#1111dd;"></i> Perfil</a></li>
                    <li><a href="#"><i class="glyphicon glyphicon-dashboard" style="color:#0000aa;"></i> Dashboard</a></li>
                    <li class="nav-divider"></li>
                    <li><a href="#"><i class="glyphicon glyphicon-cog" style="color:#dd1111;"></i> Settings</a></li>
                    <li><a href="#"><i class="glyphicon glyphicon-plus"></i> Mais..</a></li>
                </ul>


                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse2">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

            </div>
            <div class="collapse navbar-collapse" id="navbar-collapse2">
                <?php
                    $uri = $_SERVER['REQUEST_URI'];
                ?>

                <ul id="menu" class="nav navbar-nav navbar-right">
                    <li class="<?php echo  $uri == '/pessoa' ? 'active' : '' ?>"><a href="/pessoa">Minha Página</a></li>
                    <li class="<?php echo  $uri == '/pessoa/instituicao' ? 'active' : '' ?>"><a href="/pessoa/instituicao">Instituições</a></li>
                    <li class="<?php echo  $uri == '/pessoa/eventos' ? 'active' : '' ?>"><a href="#" role="button" data-toggle="modal">Eventos</a></li>
                    <li class="<?php echo  $uri == '/pessoa/denunciar-abusos' ? 'active' : '' ?>"><a href="#" role="button" data-toggle="modal">Denunciar Abusos</a></li>
                </ul>
            </div>
        </div>
    </div>
    </nav>
    <div class="container-fluid" id="main">
            <?php echo $this->content; ?>

        <footer>

            <hr>
            <div style="outline: 1px solid #ccc" class="col-md-12 text-center"><p><a href="http://www.bootply.com/download/90113" target="_ext">Colocar redes sociais aqui</a></p></div>
            <hr>
        </footer>

    </div> <!-- /container -->

    </body>
</html>
