<br><br><br><br>
<div class="col-xs-12">
	<div class="col-lg-6">
		<div class=" col-xs-12 padding-zero panel label-default">
			<i></i>
			<li class="list-group-item list-group-item-special">
				<b>Donativos</b>
			</li>
			<li aria-controls="perfilcollapse" aria-expanded="false" href="#donativo-1" data-toggle="collapse" class="list-group-item list-group-item-special">
				Baixo estoque de Nutren
				<br>
				<sub>Incluído em: 24/04/2015</sub>
				<span class="badge pull-rigth">Pedidos: 100</span><span class="badge pull-rigth label-info">Doados: 36</span> 
			</li>
			<ul id="donativo-1" data-toggle="collapse" class="list-flat list-group panel-body in" style="height: auto;">
				<li class="list-group-item">
					Precisamos de nutrem para incluir no estoque 
					<br>
					<sub>Expira em: 01/01/1960</sub>
					<div class="pull-right btn-group btn-group-sm">						
						<a class="btn btn-info">Editar</a>
						<a class="btn btn-danger">Desativar</a>
					</div>
				</li>
			</ul>
			<li aria-controls="perfilcollapse" aria-expanded="false" href="#donativo-1" data-toggle="collapse" class="list-group-item list-group-item-special">
				Baixo estoque de Nutren
				<br>
				<sub>Incluído em: 24/04/2015</sub>
				<span class="badge pull-rigth">Pedidos: 100</span><span class="badge pull-rigth label-info">Doados: 36</span> 
			</li>
			<ul id="donativo-1" data-toggle="collapse" class="list-flat list-group panel-body in" style="height: auto;">
				<li class="list-group-item">
					Precisamos de nutrem para incluir no estoque 
					<br>
					<sub>Expira em: 01/01/1960</sub>
					<div class="pull-right btn-group btn-group-sm">						
						<a class="btn btn-info">Editar</a>
						<a class="btn btn-danger">Desativar</a>
					</div>
				</li>
			</ul>
			<li aria-controls="perfilcollapse" aria-expanded="false" href="#donativo-1" data-toggle="collapse" class="list-group-item list-group-item-special">
				Baixo estoque de Nutren
				<br>
				<sub>Incluído em: 24/04/2015</sub>
				<span class="badge pull-rigth">Pedidos: 100</span><span class="badge pull-rigth label-info">Doados: 36</span> 
			</li>
			<ul id="donativo-1" data-toggle="collapse" class="list-flat list-group panel-body in" style="height: auto;">
				<li class="list-group-item">
					Precisamos de nutrem para incluir no estoque 
					<br>
					<sub>Expira em: 01/01/1960</sub>
					<div class="pull-right btn-group btn-group-sm">						
						<a class="btn btn-info">Editar</a>
						<a class="btn btn-danger">Desativar</a>
					</div>
				</li>
			</ul>
		</div>
	</div>
	<div class="col-lg-6">
		<div class="col-xs-12 label-primary padding-zero">
			<i></i>
			<li class="list-group-item">
				Adição/Edição Pedidos
			</li>
			<form class="panel-body">
				<div class="form-group">
					<label>Título:</label>
					<input class="form-control" type="text" />
				</div>
				<div class="form-group">
					<label>Categoria:</label>
					<select class="form-control">
						<option>Alimenticios</option>
						<option>Vestuário</option>
						<option>Limpeza</option>
					</select>
				</div>
				<div class="form-group">
					<label>Detalhes:</label>
					<textarea rows="5" class="form-control"></textarea>
				</div>
				<div class="form-group btn-group btn-group-sm pull-right">
					<button type="submit" class="btn btn-success">Confirmar <i class="glyphicon glyphicon-ok"></i></button>
					<button type="submit" class="btn btn-danger">Limpar <i class="glyphicon glyphicon-remove"></i></button>
				</div>
			</form>
		</div>
	</div>
</div>