<?php
	use Zend\Form\Element\DateTime;
use Zend\Form\Element\DateTimeLocal;
echo $this->headScript()->appendFile($this->basePath . '/js/instituicao_actions.js');
	
	if($e_json = true):
		$form->setAttribute('action',$this->url('donativo',array('action'=>'validaajax')));
	else:
		$form->setAttribute('action',$this->url('donativo',array('action'=>'novo')));
	endif;
	$form->setAttribute('enctype','application/json');
	$form->prepare();
	
	echo $this->form()->openTag($form);
	echo $this->formHidden($form->get('id'));
	echo $this->formHidden($form->get('dataInclusao')->setValue(date("Y-m-d")));
	echo "<div class='form-group col-lg-8 padding-zero'>".$this->formRow($form->get('titulo'))."</div>";
	echo "<div class='form-group col-lg-2'>".$this->formRow($form->get('quantidade'))."</div>";
	echo "<div class='form-group'>".$this->formRow($form->get('descricao'))."</div>";
	echo "<div class='form-group'>".$this->formSubmit($form->get('submit'))."</div>";
	echo $this->form()->closeTag();
	
?>